// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SearchAt             string   `protobuf:"bytes,8,opt,name=search_at,json=searchAt,proto3" json:"search_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Voice                string   `protobuf:"bytes,6,opt,name=voice,proto3" json:"voice,omitempty"`
	Leg                  string   `protobuf:"bytes,7,opt,name=leg,proto3" json:"leg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Task) GetSearchAt() string {
	if m != nil {
		return m.SearchAt
	}
	return ""
}

func (m *Task) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetVoice() string {
	if m != nil {
		return m.Voice
	}
	return ""
}

func (m *Task) GetLeg() string {
	if m != nil {
		return m.Leg
	}
	return ""
}

type MakeDoneRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeDoneRequest) Reset()         { *m = MakeDoneRequest{} }
func (m *MakeDoneRequest) String() string { return proto.CompactTextString(m) }
func (*MakeDoneRequest) ProtoMessage()    {}
func (*MakeDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *MakeDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDoneRequest.Unmarshal(m, b)
}
func (m *MakeDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDoneRequest.Marshal(b, m, deterministic)
}
func (m *MakeDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDoneRequest.Merge(m, src)
}
func (m *MakeDoneRequest) XXX_Size() int {
	return xxx_messageInfo_MakeDoneRequest.Size(m)
}
func (m *MakeDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDoneRequest proto.InternalMessageInfo

func (m *MakeDoneRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type SearchTaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTaskRequest) Reset()         { *m = SearchTaskRequest{} }
func (m *SearchTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTaskRequest) ProtoMessage()    {}
func (*SearchTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *SearchTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTaskRequest.Unmarshal(m, b)
}
func (m *SearchTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTaskRequest.Marshal(b, m, deterministic)
}
func (m *SearchTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTaskRequest.Merge(m, src)
}
func (m *SearchTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTaskRequest.Size(m)
}
func (m *SearchTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTaskRequest proto.InternalMessageInfo

func (m *SearchTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type FlagResponse struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagResponse) Reset()         { *m = FlagResponse{} }
func (m *FlagResponse) String() string { return proto.CompactTextString(m) }
func (*FlagResponse) ProtoMessage()    {}
func (*FlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *FlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagResponse.Unmarshal(m, b)
}
func (m *FlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagResponse.Marshal(b, m, deterministic)
}
func (m *FlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagResponse.Merge(m, src)
}
func (m *FlagResponse) XXX_Size() int {
	return xxx_messageInfo_FlagResponse.Size(m)
}
func (m *FlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlagResponse proto.InternalMessageInfo

func (m *FlagResponse) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type SearchTaskResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTaskResponse) Reset()         { *m = SearchTaskResponse{} }
func (m *SearchTaskResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTaskResponse) ProtoMessage()    {}
func (*SearchTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *SearchTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTaskResponse.Unmarshal(m, b)
}
func (m *SearchTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTaskResponse.Marshal(b, m, deterministic)
}
func (m *SearchTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTaskResponse.Merge(m, src)
}
func (m *SearchTaskResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTaskResponse.Size(m)
}
func (m *SearchTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTaskResponse proto.InternalMessageInfo

func (m *SearchTaskResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*MakeDoneRequest)(nil), "task.MakeDoneRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "task.UpdateTaskRequest")
	proto.RegisterType((*SearchTaskRequest)(nil), "task.SearchTaskRequest")
	proto.RegisterType((*DeleteTaskRequest)(nil), "task.DeleteTaskRequest")
	proto.RegisterType((*GetAllRequest)(nil), "task.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "task.GetAllResponse")
	proto.RegisterType((*FlagResponse)(nil), "task.FlagResponse")
	proto.RegisterType((*SearchTaskResponse)(nil), "task.SearchTaskResponse")
}

func init() {
	proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff)
}

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x93, 0xd2, 0x40,
	0x10, 0x35, 0x1f, 0x20, 0x69, 0x14, 0xa4, 0xa5, 0xca, 0x29, 0x2c, 0xad, 0x38, 0x5e, 0x38, 0x71,
	0xc0, 0x2a, 0x0f, 0x7a, 0x4a, 0x41, 0xe9, 0xc9, 0x0b, 0xe8, 0xd9, 0x1a, 0xc9, 0x98, 0x4d, 0x91,
	0x4d, 0xd8, 0xcc, 0xc0, 0xbf, 0xda, 0x3f, 0xb0, 0xbf, 0x6e, 0x6b, 0x7a, 0x92, 0x25, 0x6c, 0x96,
	0x2d, 0x6e, 0x9d, 0xd7, 0xfd, 0x7a, 0xde, 0xeb, 0x57, 0x01, 0xd0, 0x42, 0x6d, 0x67, 0xbb, 0xb2,
	0xd0, 0x05, 0xfa, 0xa6, 0xe6, 0xb7, 0x0e, 0xf8, 0xbf, 0x85, 0xda, 0xe2, 0x00, 0xdc, 0x34, 0x66,
	0x4e, 0xe8, 0x4c, 0x83, 0x95, 0x9b, 0xc6, 0xf8, 0x01, 0x60, 0xbf, 0x8b, 0x85, 0x96, 0xf1, 0x5f,
	0xa1, 0x99, 0x47, 0x78, 0x50, 0x21, 0x91, 0xc6, 0xf7, 0x10, 0x28, 0x29, 0xca, 0xcd, 0x95, 0xe9,
	0xf6, 0xa8, 0xdb, 0xb3, 0x40, 0xa4, 0x0d, 0x37, 0x96, 0x99, 0xac, 0xb8, 0xbe, 0xe5, 0x56, 0x48,
	0xa4, 0x11, 0xc1, 0xcf, 0xc5, 0xb5, 0x64, 0x1d, 0x6a, 0x50, 0x8d, 0x63, 0xe8, 0x1c, 0x8a, 0x74,
	0x23, 0x59, 0x97, 0x40, 0xfb, 0x81, 0x6f, 0xc0, 0xcb, 0x64, 0xc2, 0x5e, 0x12, 0x66, 0x4a, 0xfe,
	0x09, 0x86, 0xbf, 0xc4, 0x56, 0x2e, 0x8b, 0x5c, 0xae, 0xe4, 0xcd, 0x5e, 0x2a, 0xdd, 0x50, 0xee,
	0x1b, 0xe5, 0x7c, 0x01, 0xa3, 0x3f, 0xa4, 0xd3, 0xf8, 0x6a, 0x0f, 0x79, 0x64, 0xef, 0x23, 0x90,
	0x7f, 0xe6, 0x86, 0xce, 0xb4, 0x3f, 0x87, 0x19, 0x1d, 0x86, 0x08, 0xf6, 0x2e, 0x0b, 0x18, 0xad,
	0xc9, 0xce, 0xd3, 0x4b, 0x82, 0x8b, 0x96, 0x7c, 0x86, 0xd1, 0x92, 0x5c, 0x3f, 0xa3, 0x84, 0x0f,
	0xe1, 0xf5, 0x4f, 0xa9, 0xa3, 0x2c, 0xab, 0x06, 0xf8, 0x1c, 0x06, 0x35, 0xa0, 0x76, 0x45, 0xae,
	0x24, 0x86, 0xd0, 0x31, 0xfb, 0x14, 0x73, 0x42, 0xef, 0xd1, 0x43, 0xb6, 0xc1, 0x39, 0xbc, 0xfa,
	0x91, 0x89, 0xe4, 0x81, 0x81, 0xe0, 0xff, 0xcf, 0x44, 0x42, 0xcf, 0xf4, 0x56, 0x54, 0xf3, 0xaf,
	0x80, 0x4d, 0x4b, 0x97, 0xee, 0x9e, 0xdf, 0xb9, 0xe6, 0xe6, 0xb9, 0x48, 0xd2, 0x3c, 0x59, 0xcb,
	0xf2, 0x60, 0x82, 0x99, 0x01, 0x2c, 0x4a, 0x59, 0xdd, 0x18, 0x1b, 0xa4, 0x09, 0xda, 0xba, 0xa9,
	0x86, 0xbf, 0xc0, 0xef, 0x00, 0xc7, 0x4c, 0xf0, 0x9d, 0x9d, 0x69, 0xa5, 0x74, 0x86, 0x1c, 0x01,
	0x1c, 0x85, 0xd7, 0xe4, 0x56, 0x3a, 0x13, 0xd6, 0x6e, 0x34, 0xdf, 0x3f, 0x26, 0x51, 0xaf, 0x68,
	0x65, 0x73, 0xe6, 0xfd, 0x6f, 0xd0, 0xb7, 0x81, 0x98, 0x51, 0x85, 0x6f, 0xed, 0xd0, 0x49, 0x68,
	0x93, 0xf1, 0x29, 0x58, 0x73, 0xff, 0x75, 0xe9, 0x67, 0xfb, 0x72, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0xe0, 0x4f, 0xa9, 0xf2, 0x7a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManagingServiceClient is the client API for ManagingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagingServiceClient interface {
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*FlagResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	SearchTask(ctx context.Context, in *SearchTaskRequest, opts ...grpc.CallOption) (*SearchTaskResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type managingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagingServiceClient(cc grpc.ClientConnInterface) ManagingServiceClient {
	return &managingServiceClient{cc}
}

func (c *managingServiceClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) SearchTask(ctx context.Context, in *SearchTaskRequest, opts ...grpc.CallOption) (*SearchTaskResponse, error) {
	out := new(SearchTaskResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/SearchTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagingServiceServer is the server API for ManagingService service.
type ManagingServiceServer interface {
	CreateTask(context.Context, *Task) (*FlagResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*FlagResponse, error)
	SearchTask(context.Context, *SearchTaskRequest) (*SearchTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*FlagResponse, error)
	GetAllTasks(context.Context, *GetAllRequest) (*GetAllResponse, error)
}

// UnimplementedManagingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagingServiceServer struct {
}

func (*UnimplementedManagingServiceServer) CreateTask(ctx context.Context, req *Task) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedManagingServiceServer) UpdateTask(ctx context.Context, req *UpdateTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedManagingServiceServer) SearchTask(ctx context.Context, req *SearchTaskRequest) (*SearchTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTask not implemented")
}
func (*UnimplementedManagingServiceServer) DeleteTask(ctx context.Context, req *DeleteTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (*UnimplementedManagingServiceServer) GetAllTasks(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}

func RegisterManagingServiceServer(s *grpc.Server, srv ManagingServiceServer) {
	s.RegisterService(&_ManagingService_serviceDesc, srv)
}

func _ManagingService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_SearchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).SearchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/SearchTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).SearchTask(ctx, req.(*SearchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.ManagingService",
	HandlerType: (*ManagingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ManagingService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _ManagingService_UpdateTask_Handler,
		},
		{
			MethodName: "SearchTask",
			Handler:    _ManagingService_SearchTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ManagingService_DeleteTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _ManagingService_GetAllTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
